### ISSUE TITLE
strange behaviour: reactions not working

### ISSUE THREAD

**Issue by Joduai** [pytesNET/reactions#1]
Howdy

Again me ;)
I've noticed a strange behaviour on my production bludit instance.
Basically reactions plugin doesn't want to count the votes with one excetpion. 
And it seems that it did't work even with initial release.
After checking on a fresh instance installed in nested dir, the plugin seems to work fine on my webhost, so I got back to find wth is going on on the production instance.

I don't get any crucial info in apache error log, nor any notice wants to appear, thus after some try outs I found out, that "votes" are working only on static pages, and I've got no idea why.
Static page gets an update by this plugin in databases/pages.php, but not the published and sticky. 

Tried as logged user, not logged, in different browser etc.

Do you have any idea how can I trace the bug?

--- 

There's a "1" char showing up at the beginning of page source caused by `return true` in ` function beforeSiteLoad() `

--- 

btw. when you came up with reactions plugin I think I'd ask, if you were also thinking about a star rate plugin in microformats?

**Comment by Joduai** [comment]
Ohh, right after I posted the issue I found the bug.
It's just that reactions don't work on pages having a parent set.
I'm not sure if you check the page uri in pages.php, as the nested pages get `parent\/sibling` string and I think this might cause this problem.

**Comment by SamBrishes** [comment]
Hellow,

Thanks for reporting this issue. I guess I'm using the wrong slug, which doesn't contain potential parents. 

I'll check them as fast as possible. 

-----

A star rating system sounds also good. Maybe I extend the reactions plugin with star ratings, or I create a complete new plugin. 

Sincerely, 
Sam.

**Comment by SamBrishes** [comment]
Hellow,

try out the new master branch, the problem with the child-pages should be fixed now.

Sincerely,
Sam.

**Comment by Joduai** [comment]
Everything works flawlessly.
Switching slug() to key() solved the problem :)
