### ISSUE TITLE
The number 1 shows up on top of the page where reactions are present

### ISSUE THREAD

**Issue by ShiDotMoe** [pytesNET/reactions#2]
![image](https://user-images.githubusercontent.com/7031498/57526862-d3c36a80-732e-11e9-8bb5-77ff1c8dfa24.png)
![image](https://user-images.githubusercontent.com/7031498/57526873-dde56900-732e-11e9-804b-1ea250616fac.png)

**Comment by SamBrishes** [comment]
Hellow,

thanks for reporting, I couldn't reproduce this issue, but I tried to fix it anyway. Please try out the [latest master branch](https://github.com/pytesNET/reactions/zipball/master), it should solve this issue.

Sincerely,
Sam.

**Comment by Shimeri** [comment]
Solved it. I downloaded the version from the Bludit Plugins site.

**Comment by Joduai** [comment]
@Shimeri  I posted the bug and possible fix in #1
Sam updated the plugin in no time ;)
