### ISSUE TITLE
Broken image in dashboard

### ISSUE THREAD

**Issue by DigitalAssasin** [pytesNET/reactions#4]
Hi!

I'm using the reactions plugin in my website for a while now. Awesome job! So I thought it's just fair to spend a few EUR and buy the "+" version.

With this new version, there is a new module in the dashboard which displays the latest reactions, which is great! But in the dashboard module there are broken images if I'm using the emojis.

The broken image refers to the following URL: https://cdn.jsdelivr.net/emojione/assets/4.5/png/16/1f60d.png

If I try to open this URL directly in the browser, the CDN gives me an "Access Denied" error.

Regards,

Christian

**Comment by SamBrishes** [comment]
Hellow,

thanks for your support, that's awesome :D ! 

I fixed the issue in version 1.0.1, you can download the new package directly on gumroad. Just re-visit the link which you received per eMail as you bought the package. If the download doesn't work, write me a short mail at [info@pytes.net](mailto:info@pytes.net), and I will send you the new version directly.

Thanks for reporting this issue, I apologize for the trouble.

Sam.

**Comment by DigitalAssasin** [comment]
Hi Sam,

thank you for your light speed fix ;o)

I was able to download the package using the link from the email. The new version fixes this problem. I will close this issue.

Thanks again and stay healthy!

Christian
